### ISSUE TITLE
Feature Request: Support for Configuring Custom Templates

### ISSUE THREAD

**Issue by Shaglock** [skryukov/inertia_rails-contrib#19]
#### Description

I propose adding functionality that allows developers to configure custom templates. This feature will enable users to define their own templates for Inertia.js components, enhancing flexibility and adaptability to various project requirements.

#### Motivation

The current implementation has predefined templates which may not suit all project needs. Allowing custom templates will:
- Enable developers to tailor templates to specific project requirements.
- Enhance the usability of the library across different types of Inertia.js applications.
- Promote better code reuse by allowing teams to standardize their own templates.

Thank you for considering this proposal.

**Comment by skryukov** [comment]
Hey @Shaglock thanks for the request! Could you check if this is what you're looking for: https://inertia-rails.netlify.app/guide/responses.html#customizing-the-generator-templates

**Comment by Shaglock** [comment]
Hi @skryukov, thank you for reply! Yes, thats exactly what I was looking for and couldn't find, my bad, apologies.
