### ISSUE TITLE
Fix vite HMR not working on fresh install

### ISSUE THREAD

**Issue by Admiral-Enigma** [skryukov/inertia_rails-contrib#22]
Seems to be related to this https://github.com/ElMassimo/vite_ruby/discussions/89

Basically you get an error in the console that it can't connect to localhost:3036/vite-dev.

This is then easily fixed by setting the host in the vite config explicitly to 127.0.0.1

Pretty nice package other than this small issue! Thank you for creating this

**Comment by skryukov** [comment]
Hey @Admiral-Enigma, thanks for the issue! Another option is to simply use `localhost` to access the Rails app.

I don't think we can do anything about it, so I will close the issue, but I hope it will help people struggling with the `localhost:3036/vite-dev` error to find the solution. Let me know if I can do anything else 🙌

**Comment by skryukov** [comment]
I will add that using `127.0.0.1` instead of localhost lead to some additional problems in my experience, like broken cache busting, for example, so I'd prefer not to add it to the config until `vite-ruby` is ready to do so 😅

**Comment by Admiral-Enigma** [comment]
Ahh alright, thank you. But the weird thing was that I was using localhost:3000 to access the app but still it did not work without changing the config 🤷
