### ISSUE TITLE
Scaffolding in a project using react and typescript generates .jsx files in app/frontend/pages

### ISSUE THREAD

**Issue by mpressen** [skryukov/inertia_rails-contrib#27]
It should generate .tsx files instead.

At the moment, if I don't rename manually those files, my app breaks (page is undefined in my inertia entrypoint, as it looks for .tsx extension for pages)

**Comment by mpressen** [comment]
Allright ! With the docs and now generators being merged in 'inertia_rails' as well, what is the goal for this gem next ? I see a great PR for integrating inertiaui/modal (I'll probably test it soon), but I 'm curious :p.

Thanks for all the great work

**Comment by skryukov** [comment]
Good question. I think we'll keep it as a place for experimental features that shouldn't go into the core (like modal support). Will see 😂
