### ISSUE TITLE
Vite and CSS errors after creating new project with Tailwind and Vue

### ISSUE THREAD

**Issue by JangoCG** [skryukov/inertia_rails-contrib#28]
Hey everyone
I wanted to give Rails and Inertia a try and found this gem. I've setup a brand new project following

# Inertia.js + Rails Setup Issues

## Environment
- **Framework**: Ruby on Rails (new project)
- **Frontend**: 
 - Inertia.js  
 - Vue.js with TypeScript
 - Tailwind CSS
- **Setup Guide Followed**: [Evil Martians - Inertia.js in Rails](https://evilmartians.com/chronicles/inertiajs-in-rails-a-new-era-of-effortless-integration)

### 1. Missing CSS File
GET http://127.0.0.1:3100/stylesheets/application.css
net::ERR_ABORTED 404 (Not Found)

### 2. Vite Dev Server Connection Failed
WebSocket connection to 'ws://127.0.0.1:3036/vite-dev/' failed
GET http://127.0.0.1:3036/vite-dev/ net::ERR_CONNECTION_REFUSED

## Status
- Application is generally working
- Tailwind CSS styles are being applied correctly
- These errors appear in console but don't affect core functionality

## Steps to Reproduce
1. Created new Rails project
2. Followed Evil Martians setup guide
3. Started the application
4. Opened any Inertia page

## Additional Information
- Errors appear immediately upon opening any Inertia page
- Both issues seem to be related to asset/resource loading
- Using default ports (Rails: 3100, Vite: 3036)

## Questions
1. Are these errors expected/known issues?
2. Can they be safely ignored since the app works?
3. If fixes are needed, what configuration changes are recommended?

**Comment by JangoCG** [comment]
Update: 
I found a fix for the CSS it is because in `application.html.erb` is using 2 asset system at the same time 

```
<%= stylesheet_link_tag "application" %>  <!-- Traditional Rails Asset Pipeline -->
<%= vite_stylesheet_tag "application" %>  <!-- Vite Asset Handling -->
```

The fix was to delete  <%= stylesheet_link_tag "application" %>  from the `application.html.erb`

**Comment by skryukov** [comment]
Thanks for the issue!

1. Missing CSS file comes from your `application.html.erb` — you can safely drop the css tag.
2. Vite Dev Server connection failed is [a known issue of Vite Ruby and macOS combo](https://vite-ruby.netlify.app/guide/troubleshooting.html#requests-to-vite-refuse-to-connect-for-1). I suggest using http://localhost:3100 instead of 127.0.0.1 for development

**Comment by JangoCG** [comment]
Good Morning @skryukov  
Thanks you for the fast answer. Yes that worked. Thanks a lot! 🙏
