### ISSUE TITLE
feat: Create ./bin/dev command

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [skryukov/inertia_rails-contrib#9]
# Context

https://github.com/rails/jsbundling-rails and https://github.com/rails/cssbundling-rails creates a very helpful bash script to start application with foreman that is `./bin/dev`, I think the standard rails developer that use these gems are very used to this command

# Feature request

Create `./bin/dev` bash script in initialize command.

If you guys like the idea, I can submit this PR!!

**Comment by skryukov** [comment]
Thanks for the request! Since I prefer https://github.com/DarthSim/overmind over foreman, here is `bin/dev` I currently use:

```sh
#!/usr/bin/env sh

export PORT="${PORT:-3000}"

if command -v overmind 1> /dev/null 2>&1
then
  overmind start -f Procfile.dev "$@"
  exit $?
fi

if gem list --no-installed --exact --silent foreman; then
  echo "Installing foreman..."
  gem install foreman
fi

foreman start -f Procfile.dev "$@"
```

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thanks @skryukov i think this one is perfect
